#!/usr/bin/env bash
#  Bash script display information

# Check 
if [ $# -lt 1 ]; then
  echo "Usage: $0 domain [subdomain1 subdomain2 ...]"
  exit 1
fi

# Set domain 
domain="$1"

# Set subdomains
subdomains=("www" "lb-01" "web-01" "web-02")

# If additional subdomains add them to the subdomains array
if [ $# -gt 1 ]; then
  subdomains+=("${@:2}")
fi

# Loop through subdomains
for subdomain in "${subdomains[@]}"; do
  output=$(dig "$subdomain.$domain" +short)
  if [ -n "$output" ]; then
    echo "The subdomain $subdomain has IP address $output"
  else
    echo "The subdomain $subdomain does not exist"
  fi
done
